########################################################################################################
#                                                                                                      #
#      _______  _______  _______ _________ _______  _                   _______  _______  _______      #
#     (  ____ )(  ____ \(  ____ \\__   __/(  ___  )( (    /|  |\     /|(  ___  )(  ____ )(  ____ \     #
#     | (    )|| (    \/| (    \/   ) (   | (   ) ||  \  ( |  | )   ( || (   ) || (    )|| (    \/     #
#     | (____)|| (__    | |         | |   | |   | ||   \ | |  | | _ | || (___) || (____)|| (_____      #
#     |     __)|  __)   | | ____    | |   | |   | || (\ \) |  | |( )| ||  ___  ||     __)(_____  )     #
#     | (\ (   | (      | | \_  )   | |   | |   | || | \   |  | || || || (   ) || (\ (         ) |     #
#     | ) \ \__| (____/\| (___) |___) (___| (___) || )  \  |  | () () || )   ( || ) \ \__/\____) |     #
#     |/   \__/(_______/(_______)\_______/(_______)|/    )_)  (_______)|/     \||/   \__/\_______)     #
#                                                                                                      #
#                                                                                                      #
#                                         Version: 1.0.0                                               #
#                                                                                                      #
########################################################################################################

# Language file that will be loaded by the plugin. Default: en-US.yml
language-file: en-US.yml

# Storage section
storage:
  # Specifies storage type that will be used by the plugin. Default: sqlite
  # Available storage types: sqlite
  type: sqlite

  # Specifies the username used to connect to the database. Default: regionwars
  username: regionwars
  # Specifies the password used to connect to the database. Default: changeit
  password: changeit
  # The name of the database
  database-name: regionwars
  # The url of the database. It will be concatenated with database-name like "database-url+database-name"
  database-url: localhost:3306/