########################################################################################################
#                                                                                                      #
#      _______  _______  _______ _________ _______  _                   _______  _______  _______      #
#     (  ____ )(  ____ \(  ____ \\__   __/(  ___  )( (    /|  |\     /|(  ___  )(  ____ )(  ____ \     #
#     | (    )|| (    \/| (    \/   ) (   | (   ) ||  \  ( |  | )   ( || (   ) || (    )|| (    \/     #
#     | (____)|| (__    | |         | |   | |   | ||   \ | |  | | _ | || (___) || (____)|| (_____      #
#     |     __)|  __)   | | ____    | |   | |   | || (\ \) |  | |( )| ||  ___  ||     __)(_____  )     #
#     | (\ (   | (      | | \_  )   | |   | |   | || | \   |  | || || || (   ) || (\ (         ) |     #
#     | ) \ \__| (____/\| (___) |___) (___| (___) || )  \  |  | () () || )   ( || ) \ \__/\____) |     #
#     |/   \__/(_______/(_______)\_______/(_______)|/    )_)  (_______)|/     \||/   \__/\_______)     #
#                                                                                                      #
#                                                                                                      #
#                                         Version: 1.0.0                                               #
#                                                                                                      #
########################################################################################################

# Language file that will be loaded by the plugin. Default: en-US.yml
language-file: en-US.yml